name: Continuous Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    environment: AWS_DEPLOYMENT

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up SSH key
      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Configure AWS CLI
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Change this to your desired AWS region

      # Step 4: Get EC2 Public IP
      - name: Get EC2 Public IP
        id: ec2info
        run: |
          INSTANCE_ID=i-039c1f8227270d4e5
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      # Step 5: Deploy application to EC2
      - name: Deploy Code to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@$PUBLIC_IP <<EOF
          # Create a directory for the application
          mkdir -p /home/ubuntu/my_flask_app
          cd /home/ubuntu/my_flask_app
          # Pull the latest code
          git pull origin main
          # Activate virtual environment
          source venv/bin/activate
          # Install dependencies
          pip install -r requirements.txt
          # Restart the Flask application service
          sudo systemctl restart your_flask_app.service
          EOF
        env:
          PUBLIC_IP: ${{ env.PUBLIC_IP }}

      # Step 6: Confirm Deployment
      - name: Confirm Deployment
        run: echo "Application deployed successfully to EC2 instance."
